from pathlib import Path
from PIL import Image, ImageDraw
import textwrap

OUTPUT_DIR = Path("generated/images")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def generate_image(
    prompt: str,
    filename: str = "comic_panel.png"
) -> str:

    if not prompt:
        raise ValueError("Image prompt cannot be empty.")

    output_path = OUTPUT_DIR / filename

    width = 1024
    height = 768

    image = Image.new(
        "RGB",
        (width, height),
        "white"
    )

    draw = ImageDraw.Draw(image)

    # Border
    draw.rectangle(
        [10, 10, width - 10, height - 10],
        outline="black",
        width=8
    )

    # Header
    draw.text(
        (40, 35),
        "COMICCRAFT AI PANEL",
        fill="black"
    )

    draw.text(
        (40, 110),
        "AI Image Prompt:",
        fill="black"
    )

    # Prompt text
    wrapped = textwrap.wrap(
        prompt,
        width=65
    )

    y = 150

    for line in wrapped[:18]:

        draw.text(
            (50, y),
            line,
            fill="black"
        )

        y += 30

    # Footer
    draw.text(
        (40, height - 60),
        "Generated by ComicCraft",
        fill="black"
    )

    image.save(output_path)

    print(
        "Demo image saved:",
        output_path
    )

    return str(output_path)